---
title: "Lesson 6: summary" 
author: "Boaz"
date: "2024-08-21"
output:
  learnr::tutorial:
    progressive: true
    allow_skip: true
runtime: shiny_prerendered  
editor_options: 
  markdown: 
    wrap: 72
---

```{=html}
<style>
h1, h2, h3, h4, h5, h6 {
  direction: rtl;
}
p {
  direction: rtl;
}

.text-block1 {
  direction: rtl;       /* Set text direction to right-to-left */
  text-align: right;
  background-color: #f0f0f0; /* Light grey background */
  padding: 10px;
  border-radius: 5px;
  border: 1px solid #ddd; /* Light border */
  margin: 10px 0; /* Space around the block */
  
</style>
```
```{r setup, include=FALSE}
library(learnr)
library(gradethis)

tutorial_options(
  exercise.timelimit = 60,
  # A simple checker function that just returns the message in the check chunk
  exercise.checker = function(check_code, ...) {
    list(
      message = eval(parse(text = check_code)),
      correct = logical(0),
      type = "info",
      location = "append"
    )
  }
)

knitr::opts_chunk$set(error = TRUE)
gradethis::gradethis_setup()
```

```{r prepare-df1}
df1 = data.frame(subject = 1:6,
                city = c("Jerusalem","Haifa","Tel-Aviv","Eilat","Jerusalem","Tel-Aviv"),
                self_efficacy_score = c(2.3, 2.5, 2.1, 3, 2.2, 2.6))
```

## מבוא

הסבר קצר

## חלק ראשון - חישוב ציוני השאלון

### חישוב ממוצע השאלון

### סינון תצפיות חריגות ובעייתיות

### סיכומים תיאוריים

## חלק שני - עיבוד תוצאות המטלה



### סינון תצפיות בעייתיות

### תרשימים תיאוריים

### הפקת מדדי ביצוע

## שילוב הנתונים

### הפקת תרשימים

### שמירה

## שאלות לסיכום







